//! The single source of truth: every content-facing scripting method.
//!
//! Grouped by receiver, in source-module order, so it reads as a manifest. Read
//! rows are added in Phase C; write rows in Phase D.
//!
//! Divergence decisions baked in here (design §8 step 0):
//! - `m`/`f`/`role` `getName` resolve `effective_name()` (display name), NOT the raw
//!   spawn `core.name`. Rhai `role.getName` previously returned the spawn name; the
//!   unified accessor adopts the prose behavior. `getName` is ADDED to `m`/`f` (the
//!   Rhai surface lacked it).
//! - `w.getSkill` unknown id → error (matches Rhai, NOT the snapshot's silent 0).
//! - intentionally-unvalidated id args (`hasStuff`, `getStat`, flags, …) are `Str`.

use super::ArgShape as Arg;
use super::Contexts;
use super::Receiver::{self as R};
use super::{read, write, Accessor, MethodDescriptor, ReadFn, WriteFn};
use crate::script::validate::IdKind;

/// Compact read-row constructor.
const fn rd(
    receiver: R,
    name: &'static str,
    args: Arg,
    contexts: Contexts,
    f: ReadFn,
) -> MethodDescriptor {
    MethodDescriptor {
        receiver,
        name,
        args,
        contexts,
        accessor: Accessor::Read(f),
    }
}

/// Compact write-row constructor (always `Contexts::WRITE`).
const fn wr(receiver: R, name: &'static str, args: Arg, f: WriteFn) -> MethodDescriptor {
    MethodDescriptor {
        receiver,
        name,
        args,
        contexts: Contexts::WRITE,
        accessor: Accessor::Write(f),
    }
}

const READ: Contexts = Contexts::READ;
const COND: Contexts = Contexts::COND;
const INT: Arg = Arg::Int { i8_range: false };
const INT8: Arg = Arg::Int { i8_range: true };

pub static REGISTRY: &[MethodDescriptor] = &[
    // ── w (player) reads ──────────────────────────────────────────────────────
    rd(
        R::W,
        "hasTrait",
        Arg::Id(IdKind::Trait),
        READ,
        read::player::has_trait,
    ),
    rd(R::W, "isVirgin", Arg::None, READ, read::player::is_virgin),
    rd(
        R::W,
        "isAnalVirgin",
        Arg::None,
        READ,
        read::player::is_anal_virgin,
    ),
    rd(R::W, "isDrunk", Arg::None, READ, read::player::is_drunk),
    rd(
        R::W,
        "isVeryDrunk",
        Arg::None,
        READ,
        read::player::is_very_drunk,
    ),
    rd(
        R::W,
        "isMaxDrunk",
        Arg::None,
        READ,
        read::player::is_max_drunk,
    ),
    rd(R::W, "isSingle", Arg::None, READ, read::player::is_single),
    rd(R::W, "isOnPill", Arg::None, READ, read::player::is_on_pill),
    rd(
        R::W,
        "isPregnant",
        Arg::None,
        READ,
        read::player::is_pregnant,
    ),
    rd(
        R::W,
        "alwaysFemale",
        Arg::None,
        READ,
        read::player::always_female,
    ),
    rd(R::W, "hasStuff", Arg::Str, READ, read::player::has_stuff),
    rd(R::W, "wasMale", Arg::None, READ, read::player::was_male),
    rd(
        R::W,
        "wasTransformed",
        Arg::None,
        READ,
        read::player::was_transformed,
    ),
    rd(
        R::W,
        "hasSmoothLegs",
        Arg::None,
        READ,
        read::player::has_smooth_legs,
    ),
    // checkSkill/checkSkillRed are CONDITION-ONLY (RNG side effect on the roll cache).
    rd(
        R::W,
        "checkSkill",
        Arg::IdInt(IdKind::Skill),
        COND,
        read::player::check_skill,
    ),
    rd(
        R::W,
        "checkSkillRed",
        Arg::IdInt(IdKind::Skill),
        COND,
        read::player::check_skill_red,
    ),
    rd(
        R::W,
        "hadTraitBefore",
        Arg::Id(IdKind::Trait),
        READ,
        read::player::had_trait_before,
    ),
    rd(
        R::W,
        "inCategory",
        Arg::Id(IdKind::Category),
        READ,
        read::player::in_category,
    ),
    rd(
        R::W,
        "beforeInCategory",
        Arg::Id(IdKind::Category),
        READ,
        read::player::before_in_category,
    ),
    rd(R::W, "getMoney", Arg::None, READ, read::player::get_money),
    rd(R::W, "getStress", Arg::None, READ, read::player::get_stress),
    rd(
        R::W,
        "getAnxiety",
        Arg::None,
        READ,
        read::player::get_anxiety,
    ),
    rd(
        R::W,
        "getSkill",
        Arg::Id(IdKind::Skill),
        READ,
        read::player::get_skill,
    ),
    rd(R::W, "composure", Arg::None, READ, read::player::composure),
    rd(R::W, "pcOrigin", Arg::None, READ, read::player::pc_origin),
    rd(
        R::W,
        "beforeName",
        Arg::None,
        READ,
        read::player::before_name,
    ),
    rd(
        R::W,
        "beforeRace",
        Arg::None,
        READ,
        read::player::before_race,
    ),
    rd(R::W, "beforeAge", Arg::None, READ, read::player::before_age),
    rd(
        R::W,
        "beforeSexuality",
        Arg::None,
        READ,
        read::player::before_sexuality,
    ),
    rd(R::W, "getName", Arg::None, READ, read::player::get_name),
    rd(R::W, "getRace", Arg::None, READ, read::player::get_race),
    rd(R::W, "getAge", Arg::None, READ, read::player::get_age),
    rd(
        R::W,
        "getArousal",
        Arg::None,
        READ,
        read::player::get_arousal,
    ),
    rd(
        R::W,
        "getAlcohol",
        Arg::None,
        READ,
        read::player::get_alcohol,
    ),
    rd(R::W, "getHeight", Arg::None, READ, read::player::get_height),
    rd(R::W, "getFigure", Arg::None, READ, read::player::get_figure),
    rd(
        R::W,
        "getBreasts",
        Arg::None,
        READ,
        read::player::get_breasts,
    ),
    rd(R::W, "getButt", Arg::None, READ, read::player::get_butt),
    rd(R::W, "getWaist", Arg::None, READ, read::player::get_waist),
    rd(R::W, "getLips", Arg::None, READ, read::player::get_lips),
    rd(
        R::W,
        "getHairColour",
        Arg::None,
        READ,
        read::player::get_hair_colour,
    ),
    rd(
        R::W,
        "getHairLength",
        Arg::None,
        READ,
        read::player::get_hair_length,
    ),
    rd(
        R::W,
        "getEyeColour",
        Arg::None,
        READ,
        read::player::get_eye_colour,
    ),
    rd(
        R::W,
        "getSkinTone",
        Arg::None,
        READ,
        read::player::get_skin_tone,
    ),
    rd(
        R::W,
        "getComplexion",
        Arg::None,
        READ,
        read::player::get_complexion,
    ),
    rd(
        R::W,
        "getAppearance",
        Arg::None,
        READ,
        read::player::get_appearance,
    ),
    rd(
        R::W,
        "getNippleSensitivity",
        Arg::None,
        READ,
        read::player::get_nipple_sensitivity,
    ),
    rd(
        R::W,
        "getClitSensitivity",
        Arg::None,
        READ,
        read::player::get_clit_sensitivity,
    ),
    rd(
        R::W,
        "getPubicHair",
        Arg::None,
        READ,
        read::player::get_pubic_hair,
    ),
    rd(
        R::W,
        "getNaturalPubicHair",
        Arg::None,
        READ,
        read::player::get_natural_pubic_hair,
    ),
    rd(
        R::W,
        "getInnerLabia",
        Arg::None,
        READ,
        read::player::get_inner_labia,
    ),
    rd(
        R::W,
        "getWetness",
        Arg::None,
        READ,
        read::player::get_wetness,
    ),
    rd(
        R::W,
        "beforeVoice",
        Arg::None,
        READ,
        read::player::before_voice,
    ),
    rd(
        R::W,
        "beforeHeight",
        Arg::None,
        READ,
        read::player::before_height,
    ),
    rd(
        R::W,
        "beforeHairColour",
        Arg::None,
        READ,
        read::player::before_hair_colour,
    ),
    rd(
        R::W,
        "beforeEyeColour",
        Arg::None,
        READ,
        read::player::before_eye_colour,
    ),
    rd(
        R::W,
        "beforeSkinTone",
        Arg::None,
        READ,
        read::player::before_skin_tone,
    ),
    rd(
        R::W,
        "beforePenisSize",
        Arg::None,
        READ,
        read::player::before_penis_size,
    ),
    rd(
        R::W,
        "beforeFigure",
        Arg::None,
        READ,
        read::player::before_figure,
    ),
    // ── gd (game data) reads ──────────────────────────────────────────────────
    rd(
        R::Gd,
        "hasGameFlag",
        Arg::Str,
        READ,
        read::game_data::has_game_flag,
    ),
    rd(
        R::Gd,
        "isWeekday",
        Arg::None,
        READ,
        read::game_data::is_weekday,
    ),
    rd(
        R::Gd,
        "isWeekend",
        Arg::None,
        READ,
        read::game_data::is_weekend,
    ),
    rd(
        R::Gd,
        "arcStarted",
        Arg::Str,
        READ,
        read::game_data::arc_started,
    ),
    rd(
        R::Gd,
        "npcLikingAtLeast",
        Arg::StrStr,
        READ,
        read::game_data::npc_liking_at_least,
    ),
    rd(R::Gd, "week", Arg::None, READ, read::game_data::week),
    rd(R::Gd, "day", Arg::None, READ, read::game_data::day),
    rd(R::Gd, "desire", Arg::None, READ, read::game_data::desire),
    rd(R::Gd, "getStat", Arg::Str, READ, read::game_data::get_stat),
    rd(
        R::Gd,
        "timeSlot",
        Arg::None,
        READ,
        read::game_data::time_slot,
    ),
    rd(
        R::Gd,
        "getJobTitle",
        Arg::None,
        READ,
        read::game_data::get_job_title,
    ),
    rd(
        R::Gd,
        "arcState",
        Arg::Str,
        READ,
        read::game_data::arc_state,
    ),
    rd(
        R::Gd,
        "npcLiking",
        Arg::Str,
        READ,
        read::game_data::npc_liking,
    ),
    // ── m (active male) reads ─────────────────────────────────────────────────
    rd(R::M, "isPartner", Arg::None, READ, read::npc::m_is_partner),
    rd(R::M, "isFriend", Arg::None, READ, read::npc::m_is_friend),
    rd(
        R::M,
        "isCohabiting",
        Arg::None,
        READ,
        read::npc::m_is_cohabiting,
    ),
    rd(
        R::M,
        "isContactable",
        Arg::None,
        READ,
        read::npc::m_is_contactable,
    ),
    rd(R::M, "hadOrgasm", Arg::None, READ, read::npc::m_had_orgasm),
    rd(
        R::M,
        "hasTrait",
        Arg::Id(IdKind::NpcTrait),
        READ,
        read::npc::m_has_trait,
    ),
    rd(
        R::M,
        "isNpcAttractionOk",
        Arg::None,
        READ,
        read::npc::m_is_npc_attraction_ok,
    ),
    rd(
        R::M,
        "isNpcAttractionLust",
        Arg::None,
        READ,
        read::npc::m_is_npc_attraction_lust,
    ),
    rd(
        R::M,
        "isWAttractionOk",
        Arg::None,
        READ,
        read::npc::m_is_w_attraction_ok,
    ),
    rd(
        R::M,
        "isNpcLoveCrush",
        Arg::None,
        READ,
        read::npc::m_is_npc_love_crush,
    ),
    rd(
        R::M,
        "isNpcLoveSome",
        Arg::None,
        READ,
        read::npc::m_is_npc_love_some,
    ),
    rd(
        R::M,
        "isWLoveCrush",
        Arg::None,
        READ,
        read::npc::m_is_w_love_crush,
    ),
    rd(R::M, "hasFlag", Arg::Str, READ, read::npc::m_has_flag),
    rd(R::M, "hasRole", Arg::Str, READ, read::npc::m_has_role),
    rd(R::M, "getLiking", Arg::None, READ, read::npc::m_get_liking),
    rd(R::M, "getLove", Arg::None, READ, read::npc::m_get_love),
    rd(
        R::M,
        "getAttraction",
        Arg::None,
        READ,
        read::npc::m_get_attraction,
    ),
    rd(
        R::M,
        "getBehaviour",
        Arg::None,
        READ,
        read::npc::m_get_behaviour,
    ),
    // getName ADDED to m (effective_name).
    rd(R::M, "getName", Arg::None, READ, read::npc::m_get_name),
    // ── f (active female) reads ───────────────────────────────────────────────
    rd(R::F, "isPartner", Arg::None, READ, read::npc::f_is_partner),
    rd(R::F, "isFriend", Arg::None, READ, read::npc::f_is_friend),
    rd(
        R::F,
        "isPregnant",
        Arg::None,
        READ,
        read::npc::f_is_pregnant,
    ),
    rd(R::F, "isVirgin", Arg::None, READ, read::npc::f_is_virgin),
    rd(R::F, "hasFlag", Arg::Str, READ, read::npc::f_has_flag),
    rd(R::F, "hasRole", Arg::Str, READ, read::npc::f_has_role),
    rd(R::F, "getLiking", Arg::None, READ, read::npc::f_get_liking),
    rd(R::F, "getLove", Arg::None, READ, read::npc::f_get_love),
    rd(
        R::F,
        "getAttraction",
        Arg::None,
        READ,
        read::npc::f_get_attraction,
    ),
    rd(
        R::F,
        "getBehaviour",
        Arg::None,
        READ,
        read::npc::f_get_behaviour,
    ),
    // getName ADDED to f (effective_name).
    rd(R::F, "getName", Arg::None, READ, read::npc::f_get_name),
    // ── role (role-bound NPC) reads — role id is source-arg 0 ──────────────────
    rd(R::Role, "isPartner", Arg::Str, READ, read::role::is_partner),
    rd(R::Role, "isFriend", Arg::Str, READ, read::role::is_friend),
    rd(
        R::Role,
        "isContactable",
        Arg::Str,
        READ,
        read::role::is_contactable,
    ),
    rd(
        R::Role,
        "isPregnant",
        Arg::Str,
        READ,
        read::role::is_pregnant,
    ),
    rd(R::Role, "isVirgin", Arg::Str, READ, read::role::is_virgin),
    rd(R::Role, "hadOrgasm", Arg::Str, READ, read::role::had_orgasm),
    rd(R::Role, "hasFlag", Arg::StrStr, READ, read::role::has_flag),
    rd(R::Role, "hasRole", Arg::StrStr, READ, read::role::has_role),
    // getName lifted to effective_name() (headline divergence fix).
    rd(R::Role, "getName", Arg::Str, READ, read::role::get_name),
    rd(R::Role, "getLiking", Arg::Str, READ, read::role::get_liking),
    rd(R::Role, "getLove", Arg::Str, READ, read::role::get_love),
    rd(
        R::Role,
        "getAttraction",
        Arg::Str,
        READ,
        read::role::get_attraction,
    ),
    rd(
        R::Role,
        "getBehaviour",
        Arg::Str,
        READ,
        read::role::get_behaviour,
    ),
    // ── scene (scene-local flags) reads ───────────────────────────────────────
    rd(R::Scene, "hasFlag", Arg::Str, READ, read::scene::has_flag),
    // ── w (player) writes ─────────────────────────────────────────────────────
    wr(R::W, "changeStress", INT, write::player::change_stress),
    wr(R::W, "changeMoney", INT, write::player::change_money),
    wr(R::W, "changeAnxiety", INT, write::player::change_anxiety),
    wr(
        R::W,
        "changeComposure",
        INT,
        write::player::change_composure,
    ),
    wr(R::W, "addArousal", INT8, write::player::add_arousal),
    wr(R::W, "changeAlcohol", INT8, write::player::change_alcohol),
    wr(
        R::W,
        "skillIncrease",
        Arg::IdInt(IdKind::Skill),
        write::player::skill_increase,
    ),
    wr(
        R::W,
        "addTrait",
        Arg::Id(IdKind::Trait),
        write::player::add_trait,
    ),
    wr(
        R::W,
        "removeTrait",
        Arg::Id(IdKind::Trait),
        write::player::remove_trait,
    ),
    wr(R::W, "addStuff", Arg::Str, write::player::add_stuff),
    wr(R::W, "removeStuff", Arg::Str, write::player::remove_stuff),
    wr(R::W, "setVirgin", Arg::StrOpt, write::player::set_virgin),
    wr(R::W, "setPartner", Arg::Str, write::player::set_partner),
    wr(R::W, "addFriend", Arg::Str, write::player::add_friend),
    // ── gd (game data) writes ─────────────────────────────────────────────────
    wr(
        R::Gd,
        "setGameFlag",
        Arg::Str,
        write::game_data::set_game_flag,
    ),
    wr(
        R::Gd,
        "removeGameFlag",
        Arg::Str,
        write::game_data::remove_game_flag,
    ),
    wr(
        R::Gd,
        "addStat",
        Arg::IdInt(IdKind::Stat),
        write::game_data::add_stat,
    ),
    wr(
        R::Gd,
        "setStat",
        Arg::IdInt(IdKind::Stat),
        write::game_data::set_stat,
    ),
    wr(
        R::Gd,
        "setJobTitle",
        Arg::Str,
        write::game_data::set_job_title,
    ),
    wr(R::Gd, "addDesire", INT, write::game_data::add_desire),
    wr(R::Gd, "setDesire", INT, write::game_data::set_desire),
    wr(R::Gd, "advanceTime", INT, write::game_data::advance_time),
    // advanceArc(arc, state) — Id(Arc) is the only 2-source-arg Id (state validated).
    wr(
        R::Gd,
        "advanceArc",
        Arg::Id(IdKind::Arc),
        write::game_data::advance_arc,
    ),
    wr(
        R::Gd,
        "failRedCheck",
        Arg::Id(IdKind::Skill),
        write::game_data::fail_red_check,
    ),
    // ── scene (scene-local flags) writes ──────────────────────────────────────
    wr(R::Scene, "setFlag", Arg::Str, write::scene::set_flag),
    wr(R::Scene, "removeFlag", Arg::Str, write::scene::remove_flag),
    // ── npc(ref).* writes — ref injected as ApiArg index 0 by the adapter ──────
    // The constructor `npc(ref)` is gate-visible here but handled specially by the
    // Rhai adapter (no-op accessor; see write::npc::npc_ctor).
    wr(R::Npc, "npc", Arg::Str, write::npc::npc_ctor),
    wr(R::Npc, "addLiking", INT8, write::npc::add_liking),
    wr(R::Npc, "addLove", INT8, write::npc::add_love),
    wr(R::Npc, "addWLiking", INT8, write::npc::add_w_liking),
    wr(R::Npc, "setAttraction", INT8, write::npc::set_attraction),
    wr(R::Npc, "setFlag", Arg::Str, write::npc::set_flag),
    wr(
        R::Npc,
        "addTrait",
        Arg::Id(IdKind::NpcTrait),
        write::npc::add_trait,
    ),
    wr(
        R::Npc,
        "setRelationship",
        Arg::Str,
        write::npc::set_relationship,
    ),
    wr(R::Npc, "setBehaviour", Arg::Str, write::npc::set_behaviour),
    wr(
        R::Npc,
        "setContactable",
        Arg::Bool,
        write::npc::set_contactable,
    ),
    wr(
        R::Npc,
        "addSexualActivity",
        Arg::Str,
        write::npc::add_sexual_activity,
    ),
    wr(R::Npc, "setRole", Arg::Str, write::npc::set_role),
    wr(R::Npc, "setName", Arg::Str, write::npc::set_name),
];
